spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Notes?serverTimezone=UTC&&useSSL=true&requireSSL=false
    username: root
    password: "!XYMAJls1006"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
#      ddl-auto: update
      globally_quote_identifiers: true
      format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    async:
      request-timeout: 10000
server:
  port: 8081
  error:
    path: /user/error
    whitelabel:
      enabled: false
